### ISSUE TITLE
feature request: add github_team_repository data source

### ISSUE THREAD

**Issue by jlesquembre** [integrations/terraform-provider-github#1286] opened 2022-09-14 09:17 UTC
Currently there is a [github_team_repository resource](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository) to grant a particular team permissions on a particular repository.

I think it would be useful to have a `github_team_repository` data source to query permissions on a repository

**Comment by mdb** [comment] 2022-10-02 10:41
Hi @jlesquembre - I'm not a `terraform-provider-github` maintainer (I'm just a community member and user :) ) and so I can't speak on behalf of the maintainers, but I do see the following...

1. [repository_teams](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository_teams) used to "retrieve the list of teams which have access to a GitHub repository", and which features a `teams` attribute homing a list of teams with access to the repository
1. [github_team](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/team), which features a `repositories` attribute, which homes a list of team repositories

Do those existing data sources address your need (particularly `repository_teams`) and negate the value of a `github_team_repository`, or have I misinterpreted?

**Comment by alexlo03** [comment] 2022-11-21 18:19
dupe of https://github.com/integrations/terraform-provider-github/issues/1160

**Closed** 2022-11-21 18:47 UTC
