### ISSUE TITLE
Struct for bypass missing github apps?

### ISSUE THREAD

**Issue by snuggie12** [integrations/terraform-provider-github#1372] opened 2022-11-18 20:27 UTC
I keep getting an infinite loop of terraform wanting to add a github app as something that can bypass:

```
2022-11-18T13:06:52.013-0700 [WARN]  Provider "registry.terraform.io/integrations/github" produced an unexpected new value for module.soroban.github_branch_protection.main["main"] during refresh.
      - .required_pull_request_reviews[0].pull_request_bypassers: planned set element cty.StringVal("<REDACTED_GH_APP_NODE_ID>") does not correlate with any element in actual
```

Is it because apps are missing in the struct [here](https://github.com/integrations/terraform-provider-github/blob/156b7ea01334b7b91ccd6286362398e3e8aad54f/github/util_v4_branch_protection.go#L32-L37)?

**Comment by kfcampbell** [comment] 2022-11-28 22:21
This is a duplicate of #1367; let's continue future conversation there.

**Closed by kfcampbell** 2022-11-28 22:21 UTC
Labels: Type: Bug, Duplicate
