### ISSUE TITLE
[FEAT]: Resource for Configuration Variables

### ISSUE THREAD

**Issue by jamesignatius-cart** [integrations/terraform-provider-github#1495] opened 2023-01-18 17:52 UTC
### Describe the need

GitHub released the new "Configuration Variables" feature. These are basically the same as Actions Secrets, but are exposed as plain-text and unencrypted.

https://github.blog/2023-01-10-introducing-required-workflows-and-configuration-variables-to-github-actions/#configuration-variables

Only being able to pass values as sensitive/unreadable has been a pain-point for terraforming github resources. Creating the following resources would be very helpful
"github-actions-environment-variable"
"github-actions-repository-variable"
"github-actions-organization-variable"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment] 2023-01-18 18:32
I believe those resources would be using [these APIs](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28).

**Comment by LucasPickering** [comment] 2023-01-20 16:24
Is this a duplicate of #1479?

**Comment by kfcampbell** [comment] 2023-01-21 00:16
Oh, good call @LucasPickering! Let's close this issue and continue further conversation there.

**Closed by kfcampbell** 2023-01-21 00:16 UTC
Labels: Type: Feature, Status: Up for grabs, Priority: Normal
