### ISSUE TITLE
[bug]: github_branch does not refresh state if branch have been deleted

### ISSUE THREAD

**Issue by nikophil** [integrations/terraform-provider-github#981] opened 2021-11-19 17:12 UTC
Hello,

I'm trying to update some files in the repositories with terraform.

What I want to achieve is to create a PR on my repositories with some modified files. The problem occurs when the PR gets merged and the branch is deleted by github itself. When applying another time I get a 404 error when creating the file.

### Terraform Version
```bash
$ tf -v
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/github v4.18.0
+ provider registry.terraform.io/integrations/github v4.18.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch
- github_repository_file

### Terraform Configuration Files
```hcl
resource "github_branch" "dependabot" {
  repository = "repo"
  branch     = "terraform-dependabot"
}

resource "github_repository_file" "dependabot" {
  repository = "repo"
  branch              = "terraform-dependabot"
  file                = ".github/dependabot.yml"
  content             = file("github-conf-files/dependabot.yml")
  commit_message      = "chore: Dependabot file updated by terraform"
  commit_author       = data.github_user.self.login
  commit_email        = "terraform-arte@github.com"
  overwrite_on_create = true
}

resource "github_repository_pull_request" "dependabot" {
  repository = "repo"
  base_ref   = "develop"
  head_ref   = "terraform-dependabot"
  title      = "chore: Dependabot file updated by terraform"
}
```

### Expected Behavior
The `resource "github_branch"` directive should refresh its state if the branch have been deleted. And then the branch should be re-created and the file should be created afterwards.

### Actual Behavior
```
│ Error: unexpected status code: 404 Not Found
│ 
│   with github_repository_file.dependabot,
│   on repository-config-files.tf line 13, in resource "github_repository_file" "dependabot":
│   13: resource "github_repository_file" "dependabot" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` # will create the branch / the file / the PR
2.  merge the PR with `delete_branch_on_merge` option activated
3. `terraform apply` # error 404 when trying to create the file: the branch does not exist

Thanks for your help :)

**Comment by toelke** [comment] 2021-11-29 12:16
FWIW, the behaviour is the same since at least 4.2.0 (the earliest version currently available in the terraform registry), but the error message was much clearer until including version 4.13.0:

```
╷
│ Error: Branch [redacted] not found in repository [redacted] or repository is not readable
│ 
│   with module.[redacted],
│   on modules/[redacted].tf line 5, in resource "github_repository_file" "[redacted]":
│    5: resource "github_repository_file" "[redacted]" {
│ 
╵
```

Does anyone have a working solution for how to handle deleted branches? E.g. when they are deleted after a PR?

**Comment by mcintyre321** [comment] 2022-02-23 11:00
@toelke Did you find a solution for this?

**Comment by toelke** [comment] 2022-02-23 11:30
"Yes". We have this in our README:

> When terraform gives you cryptic `404` errors, then the branch `terraform` was deleted in some repositoy.
> Either re-create the branch in the repository manually or remove the affected `github_repository_file` with `terraform state rm "module.[...].github_repository_file.[...]"`.

We are also toying with the idea of using this abomination:

```terraform
resource "null_resource" "local-exec" {
  for_each = var.files
  provisioner "local-exec" {
    interpreter = ["bash", "-exuc"]
    command     = <<EOC
      # first, check if the file exists in the default-branch and has the correct content
      if [ $(sha1sum <(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${var.repository}/contents/${each.key} | jq -r '.content' | base64 -d) | awk '{ printf $1;}') == ${sha1(each.value)} ]; then
        exit 0
      fi
      # then, check if the file exists in the branch and has the correct content
      if [ $(sha1sum <(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${var.repository}/contents/${each.key}?ref=${var.branch} | jq -r '.content' | base64 -d) | awk '{ printf $1;}') == ${sha1(each.value)} ]; then
        exit 0
      fi
      branch_is_new=false
      # Check if the target branch exists and create it if not
      if [ "$(curl -s -w "%%{http_code}" -X HEAD -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${var.repository}/branches/${var.branch})" == "404" ]; then
        default_branch_sha=$(curl -s -X GET -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${var.repository}/branches/${var.default_branch} | jq -r .commit.sha)
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${var.repository}/git/refs -d '{"ref": "refs/heads/${var.branch}", "sha": "'$default_branch_sha'"}'
        branch_is_new=true
      fi
      # Commit the file
      curl -H "Authorization: token $GITHUB_TOKEN" -X PUT https://api.github.com/repos/${var.repository}/contents/${each.key} -d '{"message": "commit from terraform", "content": "${base64encode(each.value)}", "branch": "${var.branch}" }'
      # If necessary, create a PR
      if [ $branch_is_new == "true" ]; then
        curl -H "Authorization: token $GITHUB_TOKEN" -X POST https://api.github.com/repos/${var.repository}/pulls -d '{"title": "Updated file via terraform", "head": "${var.branch}", "base": "${var.default_branch}" }'
      fi
    EOC
  }

  triggers = {
    always_run = "${timestamp()}"
  }
}
```

**Comment by mcintyre321** [comment] 2022-02-23 12:15
😎 very nifty

I'm trying to model "i want this file on master, if it doesn't exist, raise a PR and wait for it to be merged". Which despite being a valid expression of desired state, is a bit of a square peg round hole situation given the `resource` types we have available.

the PR, and PR branch are ephemeral, so maybe could be done using provisioners, but it's pretty grim. Maybe need a custom provider here...

**Comment by toelke** [comment] 2022-02-23 12:24
Well, my curl-snippets does exactly that: Check if the file has the correct content in the default-branch and if not, create a branch, create the file and create a PR...

**Comment by mcintyre321** [comment] 2022-02-23 12:31
Yes, I think that's pretty great what you've got there tbh, but am I right
in thinking that it won't work for managing lifetime, i.e. if I delete a
source file or do `terraform destroy` it won't clean up?

 Maybe I can do a when: destroy provisioner based off your code 🤔

**Comment by toelke** [comment] 2022-02-23 12:42
Yes, you are totally right about that.

**Comment by merkata** [comment] 2023-09-14 12:09
FWIW here's something that works for me:

protect the branch via a branch protection rule like

```hcl
resource "github_branch_protection" "templated-protect-files" {
  for_each      = toset(var.repo_names)
  repository_id = each.value
  
  pattern = "feature/template-files"
  allows_deletions = false
}
```

I'm doing this over multiple repos hence the `for_each`. When you raise a PR from this branch (I use a github actions workflow) and it gets merged, the branch just stays there. Not the most elegant thing, though it works until the issue is properly resolved.

**Closed** 2023-10-11 18:32 UTC
Labels: Type: Bug, Status: Up for grabs, r/branch, hacktoberfest
