### ISSUE TITLE
Adding the provider GitHub App to the branch protection exception list causes an error

### ISSUE THREAD

**Issue by MattMencel** [integrations/terraform-provider-github#1156] opened 2022-05-20 14:21 UTC
GitHub recently added the ability to put GitHub Apps in the branch protection exception list so the GitHub App can bypass branch protection rules. This is useful if I want to drop GitHub Action workflow templates into repos in my organization without requiring a PR, or use the FluxCD provider to bootstrap flux manifests in repos.

https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules/

However, when I tested this new feature I noticed it caused an error when Terraform attempted to create the plan.

As soon as I removed the GitHub App from the branch protection rule exception list, the plan worked correctly again.

### Terraform Version

``` sh
# terraform -v
Terraform v1.1.8
on linux_amd64
```

### Affected Resource(s)
- github_branch_protection

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "this" {
  for_each = { for branch in local.settings.protected_branches : branch.pattern => branch }

  repository_id                   = github_repository.this.node_id
  pattern                         = each.value.pattern
  enforce_admins                  = try(each.value.enforce_admins, true)
  allows_deletions                = try(each.value.allows_deletions, false)
  allows_force_pushes             = try(each.value.allows_force_pushes, false)
  required_linear_history         = try(each.value.required_linear_history, false)
  require_conversation_resolution = try(each.value.require_conversation_resolution, true)

  required_pull_request_reviews {
    dismiss_stale_reviews           = try(each.value.dismiss_stale_reviews, true)
    required_approving_review_count = try(each.value.required_approving_review_count, 1)
    require_code_owner_reviews      = try(each.value.require_code_owner_reviews, false)

    pull_request_bypassers = try(data.github_users.pull_request_bypassers[each.key].node_ids, [])
  }

  required_status_checks {
    strict   = try(each.value.strict, true)
    contexts = each.value.contexts
  }

}
```

### Expected Behavior

A plan should have been created.

### Actual Behavior

```
╷
│ Error: Something went wrong while executing your query. Please include `0681:9080:C14D4:D695D:62879F7D` when reporting this issue.
│ 
│   with module.repos["flux-system"].github_branch_protection.this["main"],
│   on ../modules/gh-repo/main.tf line 63, in resource "github_branch_protection" "this":
│   63: resource "github_branch_protection" "this" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Add the provider GitHub App to a branch protection exception list on a repo.
2. Attempt to plan that will trigger a `GET` on the branch protection rules (`github_branch_protection` resource)
3. `terraform plan`

**Comment by vgrigoruk** [comment] 2022-06-23 10:56
I experienced the same issue today. After a small investigation I've found out that `Github apps` were not added in the original PR which added support for `pull_request_bypassers` attribute:
https://github.com/integrations/terraform-provider-github/pull/1030/files#diff-b5b3ae3d317e4c199b2bc55f4806ecb01a0f7764638d573587d9d680229145b9R23-R29

**Comment by devopsrick** [comment] 2022-06-27 07:51
Yeah github apps weren't an option when this feature was rolled out.

**Comment by paymand** [comment] 2023-03-25 08:23
Looks like this was implemented here: https://github.com/integrations/terraform-provider-github/pull/1453
And the fix was released in https://github.com/integrations/terraform-provider-github/releases/tag/v5.13.0
This issue can be closed I think.

**Comment by kfcampbell** [comment] 2023-04-10 18:20
@julien-michaud do you mind creating a new issue with an appropriate description and a snippet of HCL to reproduce it?

**Closed by kfcampbell** 2023-04-10 18:20 UTC

**Comment by mering** [comment] 2023-07-07 10:57
@julien-michaud did you create a new issue?

I am having the same problem. Even import and apply fails with this error.

**Comment by Invincibear** [comment] 2025-09-03 18:20
@mering THANK YOU!

To save somebody else, this worked for me:
```
data "github_app" "my_app_name" {
  slug = "my_app_name" # do NOT prefix this org/*
}

resource "github_branch_protection" "master_branch" {
  restrict_pushes {
    push_allowances  = [data.github_app.my_app_name.node_id]
  }
}
```

You might need to enable `read` Enterprise -> Enterprise organization installations permission on whatever you're using to auth Terraform with GitHub
