### ISSUE TITLE
[BUG] github_actions_runner_group resource crashes 

### ISSUE THREAD

**Issue by ViacheslavKudinov** [integrations/terraform-provider-github#1574] opened 2023-02-27 16:52 UTC
Versions:
```
Terraform v1.3.9
on linux_amd64

Provider integrations/github v5.18.0.
```
Error:
```
github_actions_runner_group.this: Refreshing state... [id=6]
[189](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:197)

[190](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:198)
Error: Plugin did not respond
[191](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:199)

[192](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:200)
  with github_actions_runner_group.this,
[193](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:201)
  on main.tf line 1, in resource "github_actions_runner_group" "this":
[194](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:202)
   1: resource "github_actions_runner_group" "this" {
[195](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:203)

[196](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:204)
The plugin encountered an error, and failed to respond to the
[197](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:205)
plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[198](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:206)
details.
[199](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:207)
Releasing state lock. This may take a few moments...
[200](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:208)

[201](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:209)
Stack trace from the terraform-provider-github_v5.18.0 plugin:
[202](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:210)

[203](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:211)
panic: runtime error: invalid memory address or nil pointer dereference
[204](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:212)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xf0b94d]
[205](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:213)

[206](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:214)
goroutine 90 [running]:
[207](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:215)
github.com/integrations/terraform-provider-github/v5/github.resourceGithubActionsRunnerGroupRead(0xc0003b2bd0, {0xfe4d20?, 0xc000332580?})
[208](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:216)
	github.com/integrations/terraform-provider-github/v5/github/resource_github_actions_runner_group.go:203 +0x82d
[209](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:217)
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00025fe00, 0xc000a5bf40, {0xfe4d20, 0xc000332580})
[210](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:218)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
[211](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:219)
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000eae8, {0xc000b14480?, 0x4b8786?}, 0xc000b14480)
[212](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:220)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
[213](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:221)
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x11d3d80?, 0xc00000eae8}, {0x156d400, 0xc0002df8c0}, 0xc0003b24d0, 0x0)
[214](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:222)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
[215](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:223)
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001de000, {0x1570fc8, 0xc0000036c0}, 0xc000a466c0, 0xc000020a80, 0x1d4edb0, 0x0)
[216](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:224)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
[217](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:225)
google.golang.org/grpc.(*Server).handleStream(0xc0001de000, {0x1570fc8, 0xc0000036c0}, 0xc000a466c0, 0x0)
[218](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:226)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
[219](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:227)
google.golang.org/grpc.(*Server).serveStreams.func1.2()
[220](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:228)
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
[221](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:229)
created by google.golang.org/grpc.(*Server).serveStreams.func1
[222](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:230)
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
[223](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:231)

[224](https://github.com/ORG/github-config/actions/runs/4284084172/jobs/7460667224#step:3:232)
Error: The terraform-provider-github_v5.18.0 plugin crashed!
```

On versions 5.12.0-5.14.0 at least do not crash, but apply/plan always want to change the `name` and `visibility`.

On version 5.11.0 could apply and plan doesn't find `drift`.

**Comment by aminzar-access** [comment] 2023-03-07 00:13
Any update on this? Thanks.

**Comment by kfcampbell** [comment] 2023-03-10 23:18
This is a duplicate of #1553, let's continue the conversation there. The update given on that issue is applicable here as well.

**Closed by kfcampbell** 2023-03-10 23:18 UTC
Labels: Type: Bug, Status: Up for grabs, Priority: Normal
