### ISSUE TITLE
[BUG] Branch protection resource  - invalid requrest

### ISSUE THREAD

**Issue by svalevka** [integrations/terraform-provider-github#1374] opened 2022-11-20 18:12 UTC
Branch protection request resource creation fail

How to reproduce:
* provider version  5.9.0
* terraform resource
```
resource "github_branch_protection_v3" "example" {
  repository     = "terraform-github-management"
  branch         = "dev"

  required_status_checks {
    strict   = false
    contexts = ["Naming conventions / Branch"]
  }

}
```
terraform apply result
```
github_branch_protection_v3.example: Creating...
╷
│ Error: PUT https://api.github.com/repos/xxx/terraform-github-management/branches/dev/protection: 422 Invalid request.
│ 
│ No subschema in "anyOf" matched.
│ For 'properties/checks', nil is not an array.
│ Not all subschemas of "allOf" matched.
│ For 'anyOf/1', {"strict"=>false, "contexts"=>["Naming conventions / Branch"], "checks"=>nil} is not a null. []
│ 
│   with github_branch_protection_v3.example,
│   on main.tf line 1, in resource "github_branch_protection_v3" "example":
│    1: resource "github_branch_protection_v3" "example" {
```

When resource is created manually from console, I can see it fine:
```
protection=$(gh api  -H "Accept: application/vnd.github+json" /repos/${ORG}/${REPO}/branches/dev/protection)

echo $protection | jq -r '.required_status_checks'
{
  "url": "https://api.github.com/repos/xxx/terraform-github-management/branches/dev/protection/required_status_checks",
  "strict": true,
  "contexts": [
    "Naming conventions / Branch"
  ],
  "contexts_url": "https://api.github.com/repos/xxx/terraform-github-management/branches/dev/protection/required_status_checks/contexts",
  "checks": [
    {
      "context": "Naming conventions / Branch",
      "app_id": 12345
    }
  ]
}

```

**Comment by svalevka** [comment] 2022-11-20 18:19
Potentially duplicate of https://github.com/integrations/terraform-provider-github/issues/1307

**Comment by kfcampbell** [comment] 2022-11-28 22:26
This is indeed a duplicate of #1307; let's continue future conversation over there. If you're interested in opening a PR to fix this behavior, I'd be happy to review!

**Closed by kfcampbell** 2022-11-28 22:26 UTC
