### ISSUE TITLE
[BUG]: cannot set empty status checks in github_branch_protection_v3

### ISSUE THREAD

**Issue by ljw4010** [integrations/terraform-provider-github#2261] opened 2024-05-14 12:40 UTC
### Expected Behavior

```
  required_status_checks {
    strict   = true
  }
```
this configuration can work fine

### Actual Behavior

got issues:
```

│ No subschema in "anyOf" matched.
│ No subschema in "oneOf" matched.
│ Not all subschemas of "allOf" matched.
│ For 'anyOf/1', {"strict"=>true} is not a null. []
│ 
│   with github_branch_protection_v3.create_peotection_rules["master"],
```

### Terraform Version

Terraform: v1.8.0

### Affected Resource(s)

github_branch_protection_v3

### Terraform Configuration Files

```hcl
required_status_checks {
    strict   = true
  }
```

### Steps to Reproduce

```

│ No subschema in "anyOf" matched.
│ No subschema in "oneOf" matched.
│ Not all subschemas of "allOf" matched.
│ For 'anyOf/1', {"strict"=>true} is not a null. []
│ 
│   with github_branch_protection_v3.create_peotection_rules["master"],
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cfisher281** [comment] 2024-06-12 12:44
Any idea on a timeline? This has essentially broken the ability to manage branch protection rules for my organization.

**Comment by cfisher281** [comment] 2024-06-12 13:14
We are already using `github_branch_protection_v3`. That would take a lot of work to move this over.

**Comment by cfisher281** [comment] 2024-06-12 13:36
I understand, that's why I asked if there was a timeline.

**Comment by georgekaz** [comment] 2024-06-12 15:34
This is also a dupe of https://github.com/integrations/terraform-provider-github/issues/2093

**Comment by kfcampbell** [comment] 2024-06-17 22:40
Thanks @georgekaz, I'll close this and let's track it in #2093 for the future.

**Closed by kfcampbell** 2024-06-17 22:40 UTC
Labels: Type: Bug, Status: Triage
