### ISSUE TITLE
[BUG] Panic error with github_repository_environment

### ISSUE THREAD

**Issue by greg-leocare** [integrations/terraform-provider-github#1644] opened 2023-04-11 12:00 UTC
I have try with a small number of env, but that does not change anything

Context : 
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/integrations/github v5.18.3

Trace 

`Stack trace from the terraform-provider-github_v5.18.3 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x78 pc=0x100b8233c]

goroutine 27 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0x14000a7e620, {0x100f7aa60?, 0x1400009aac0?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:137 +0x3ec
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentCreate(0x10100cfc0?, {0x100f7aa60?, 0x1400009aac0})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:107 +0x228
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x140003b17c0, 0x140006fc230, 0x14000a080c0, {0x100f7aa60, 0x1400009aac0})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x3e0
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x14000196000, 0x14000c298a0, 0x100baf6ca?, 0xf?)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x1400000e008, {0x14000a7e070?, 0x0?}, 0x14000a7e070)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x6b8
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10116e580?, 0x1400000e008}, {0x1011c90b8, 0x14000a36030}, 0x14000a7e000, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400013e000, {0x1011ccc60, 0x14000702680}, 0x14000b34a20, 0x14000907710, 0x101995b60, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x1400013e000, {0x1011ccc60, 0x14000702680}, 0x14000b34a20, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x298

Error: The terraform-provider-github_v5.18.3 plugin crashed!
`

**Comment by kfcampbell** [comment] 2023-04-11 23:54
@greg-leocare were you using GitHub App authentication? I'm curious if this is a dupe of #1576.

**Comment by greg-leocare** [comment] 2023-04-12 16:03
Yes I use the GH App Auth

**Closed** 2023-04-14 18:24 UTC
