### ISSUE TITLE
[BUG]: When using separate resources to manage GitHub team members with different roles (maintainer and member), the first set of resources (maintainers) gets removed during the apply, leaving only the second set of resources (members).

### ISSUE THREAD

**Issue by Z4ck404** [integrations/terraform-provider-github#2068] opened 2023-12-20 01:14 UTC
### Expected Behavior

```
resource "github_team_members" "maintainers" {
  team_id = "builders"

  members {
    username = "maint41n3r"
    role     = "maintainer"
  }
}

resource "github_team_members" "members" {
  team_id = "builders"

  members {
    username = "m3mb3r"
    role     = "member"
  }
}
```

Both sets of resources (maintainers and members) should be created independently without removing each other.

### Actual Behavior

Not really sure if this is a bug (as both roles could be managed in the same resource) but The first set of resources (maintainers) gets removed during the apply, leaving only the second set of resources (members).

### Terraform Version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/integrations/github v5.42.0

### Affected Resource(s)

- github_team_members

### Terraform Configuration Files

```hcl
resource "github_team_members" "maintainers" {
  team_id = "builders"

  members {
    username = "maint41n3r"
    role     = "maintainer"
  }
}

resource "github_team_members" "members" {
  team_id = "builders"

  members {
    username = "m3mb3r"
    role     = "member"
  }
}
```
```


### Steps to Reproduce

_No response_

### Debug Output

_No response_

### Panic Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by o-sama** [comment] 2023-12-20 01:24
As far as I'm aware this is intended behaviour, the `github_team_membership` resource allows you to set several members and their roles (whether via repeated code or a for_each), while the `github_team_members` resource is meant to set all of the team's members, overwriting any members not managed by Terraform or this resource specifically.

**Comment by Z4ck404** [comment] 2023-12-20 01:34
> `github_team_membership`

My first intuition was to use the resource github_team_members to set all the members at once and separate them from the maintainers. And TBH github_team_membership is better for this task with a for_each as you said.

> overwriting any members not managed by Terraform or this resource specifically. 

The second resource is completely unaware of the first one thus removing the the teams created and present in the state under the first resource key name. so `not managed by Terraform` is not really correct even if it makes sense in this case. 

Thanks a lot for your reply @o-sama

**Comment by kfcampbell** [comment] 2024-01-04 18:00
I'm with @o-sama here; this is intended behavior. We do not support using multiple `github_team_members` resources to modify the same team. I'm going to close this as not planned, though please feel free to follow up here if you have further questions.

**Closed by kfcampbell** 2024-01-04 18:00 UTC
Labels: Type: Bug, Status: Triage
