### ISSUE TITLE
GitHub App / organization authentication problem

### ISSUE THREAD

**Issue by Satak** [integrations/terraform-provider-github#990] opened 2021-11-29 09:59 UTC
### Terraform Version
Terraform **v1.0.11**
on windows_amd64

### Affected Resource(s)
all, authentication is broken and handling auth with organization

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.0"
    }
  }
}

provider "github" {
  app_auth {}
}

resource "github_team" "some_team" {
  name        = "some-team"
  description = "Some cool team"
  privacy     = "closed"
}
```

### Error
`Error: This resource can only be used in the context of an organization, "" is a user.`

### Expected Behavior
Provider would successfully authenticate via my GitHub app and would use `GITHUB_OWNER` as organization.

### Actual Behavior
Provider doesn't authenticate with GitHub App. I have set these environment variables
- `GITHUB_APP_ID`
- `GITHUB_APP_INSTALLATION_ID`
- `GITHUB_APP_PEM_FILE` (content with \n)
- `GITHUB_OWNER`

Getting error message reported above. Somehow organization is not passed at all and the authentication is broken. I have also tried to put `owner` to the `github` block as plain text but getting the same error. I also tried to put all `app_auth` information to the `app_auth` block but with no lock. Need to use environment variables anyway.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Create GitHub organization
2. Create GitHub App
3. Generate PEM file from GitHub 
4. Install GitHub App
5. Set environment variables
6. Run terraform init and plan -> error message about `"" is a user`

**Comment by Satak** [comment] 2021-11-29 11:31
Maybe related to these problems: https://github.com/integrations/terraform-provider-github/issues/980

**Comment by Satak** [comment] 2023-01-30 17:23
Is there any news for this? Can someone please provide full example how auth should work with using GitHub app instead of PAT in organization. We are still using PAT after all these years

**Comment by kfcampbell** [comment] 2023-01-30 19:06
@Satak I'm unable to reproduce this error. I'm using the [app authentication](https://github.com/integrations/terraform-provider-github/tree/main/examples/app_authentication) in the repository and I'm successfully able to create a repo doing so. Does the example work for you?

**Comment by x-yuri** [comment] 2023-06-20 08:32
@Satak [Here's][a] what I've managed to figure out.

[a]: https://github.com/integrations/terraform-provider-github/issues/1361#issuecomment-1598330000

**Comment by Satak** [comment] 2023-12-21 19:43
I finally had time to test this again and indeed now I can authenticate with GitHub for GitHub organization and run Terraform changes from Terraform Cloud against GitHub using GitHub app and the environment variables.

**Comment by kfcampbell** [comment] 2024-01-05 18:29
👍 I'll go ahead and close this issue; please feel free to create new issue(s) for additional questions.

**Closed by kfcampbell** 2024-01-05 18:29 UTC
