### ISSUE TITLE
[FEAT]: Add support for configuration variables in workflows

### ISSUE THREAD

**Issue by jwenz723** [integrations/terraform-provider-github#1479] opened 2023-01-11 19:56 UTC
### Describe the need

Recently GitHub added support for configuration variables in github actions workflows: https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/

Please add support for creating configuration variables into the terraform provider. Configuration variables can be created at the organization, repository, or environment level so support for all 3 of these scopes should be added.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment] 2023-01-11 21:44
API support for that is [available](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28), but I don't see support in [google/go-github](https://github.com/google/go-github) yet. That's a prerequisite that blocks the feature from the provider until implemented.

**Comment by jwenz723** [comment] 2023-01-11 21:55
> API support for that is [available](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28), but I don't see support in [google/go-github](https://github.com/google/go-github) yet. That's a prerequisite that blocks the feature from the provider until implemented.

I've created https://github.com/google/go-github/issues/2624 to request this feature to be added into the go-github api.

**Comment by tjcorr** [comment] 2023-04-05 21:06
This looks like a dupe of #1534 which got fixed with #1569. We should be able to close this out.

**Comment by kfcampbell** [comment] 2023-04-10 23:20
Thanks @tjcorr, closing now!

**Closed by kfcampbell** 2023-04-10 23:20 UTC
Labels: Type: Feature, Priority: Normal, Status: Blocked
