### ISSUE TITLE
[BUG]: Attempting to import github_organization_ruleset crashes plugin

### ISSUE THREAD

**Issue by audunsolemdal** [integrations/terraform-provider-github#1891] opened 2023-09-13 07:50 UTC
### Expected Behavior

No plugin crash, successful import

### Actual Behavior

When importing an existing organization level ruleset, the plugin crashes. For some reason this only occurs for my branch protection rule of target "branch", not for target "tag", unsure if relevant.

### Terraform Version

Terraform v1.5.7
on linux_amd64
+ github provider 5.36.0

### Affected Resource(s)

- github_organization_ruleset

### Terraform Configuration Files

```hcl
locals {
  org_ruleset_exceptions = {

    "cp-xxx" = {
      bypass_actors = [{
        actor_id = "xxxyyy"
      }]
    }
    "cp-yyy" = {
      bypass_actors = [{
        actor_id = "zzzz"
      }]
    }
  }
}


import {
  id = xxxx
  to = github_organization_ruleset.cprepos_ruleset
}

resource "github_organization_ruleset" "cprepos_ruleset" {
  name        = "cprepos-ruleset"
  target      = "branch"
  enforcement = "evaluate"
  conditions {
    ref_name {
      include = ["cp-*"]
      exclude = keys(local.org_ruleset_exceptions)
    }
  }

  rules {
    deletion         = true
    non_fast_forward = true

    pull_request {
      dismiss_stale_reviews_on_push   = true
      require_code_owner_review       = true
      required_approving_review_count = 0
      require_last_push_approval      = true
    }
  }
}
```

### Steps to Reproduce

terraform plan

### Panic Output

```shell
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-github_v5.36.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1046050]

goroutine 116 [running]:
github.com/integrations/terraform-provider-github/v5/github.flattenConditions(0xc00000d800, 0x1)
	github.com/integrations/terraform-provider-github/v5/github/respository_rules_utils.go:180 +0x310
github.com/integrations/terraform-provider-github/v5/github.resourceGithubOrganizationRulesetRead(0xc00019ae00, {0x10de340?, 0xc00071fc80?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_organization_ruleset.go:492 +0x687
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004f28c0, 0xc00012e050, {0x10de340, 0xc00071fc80})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000115ce0, {0xc0005aff80?, 0x4b87a6?}, 0xc0005aff80)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x13093c0?, 0xc000115ce0}, {0x16c9298, 0xc000b8cae0}, 0xc00019a8c0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x16cd4d8, 0xc00050ba00}, 0xc000584ea0, 0xc000597620, 0x1f81270, 0x0)
	google.golang.org/grpc@v1.55.0/server.go:1337 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x16cd4d8, 0xc00050ba00}, 0xc000584ea0, 0x0)
	google.golang.org/grpc@v1.55.0/server.go:1714 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.55.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.55.0/server.go:957 +0x18c

Error: The terraform-provider-github_v5.36.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by o-sama** [comment] 2023-09-13 11:06
Hi @audunsolemdal, this is a duplicate of #1886 and should be addressed in #1887 🙂

**Comment by nickfloyd** [comment] 2023-09-15 21:39
As @o-sama pointed out, addressed with https://github.com/integrations/terraform-provider-github/pull/1887

**Closed by nickfloyd** 2023-09-15 21:39 UTC
Labels: Type: Bug, Status: Triage

**Comment by audunsolemdal** [comment] 2023-09-16 07:02
Just tested again now, works great thanks!
