### ISSUE TITLE
allow empty push_restrictions

### ISSUE THREAD

**Issue by lifeofguenter** [integrations/terraform-provider-github#594] opened 2020-11-10 12:53 UTC
It currently does not look like this config is possible with the `github_branch_protection` resource:

![Screen Shot 2020-11-10 at 13 52 43](https://user-images.githubusercontent.com/241073/98676569-11f27d80-235c-11eb-8929-4ff92c5a74c8.png)

**Comment by bouk** [comment] 2020-11-24 15:42
The problem is that restricts pushes is only set if the number of users that have access > 1: https://github.com/terraform-providers/terraform-provider-github/blob/e9dc4e7177785b1a5c349cb15527b263dba389ef/github/util_v4_branch_protection.go#L159

**Comment by mrodm** [comment] 2021-01-15 16:29
I have the same issue using version 4.2.0 of the provider.
If I want that check enabled, the workaround that I just found was adding a user to the list.

**Comment by fatbasstard** [comment] 2023-08-18 12:22
Hi all!

I'm hitting this same issue now. I want the option to be enabled, just as in the picture above, without specifying names. In my case I only want "maintainers" to be able to push...

This is currently not possible

**Comment by georgekaz** [comment] 2023-11-28 11:22
I've been trying to create a PR to resolve this and I just can't seem to manage it without making breaking changes. I'm not really sure what the protocol on creating breaking changes is. If I'm allowed to offer breaking changes, I have a working solution.

As it currently stands, if `push_restrictions` is defined or not, the state json stores `"push_restrictions": []`. This means that if you define it as an empty list or you don't define it at all, the state can't tell it apart. Therefore defining it empty cannot be used to enable push restrictions.

**Option 1**
You define another property in state such as `restrict_pushes = true` in order to track it. However, by adding this (with a sensible default `false`), existing deployments that do provide a list of `push_restrictions` actors will stop working unless the new property is defined. Currently this isn't needed because of line 318 here: https://github.com/integrations/terraform-provider-github/blob/46650cb363ded7c10bc780998fa3166d3dd63daf/github/util_v4_branch_protection.go#L316-L319, but this must be removed if it's controlled by the new property or it will create constant state flux.

```
restrict_pushes = true
push_restrictions = [
"/someone"
]
blocks_creations = true
```

**Option 2**
Restructure the whole thing in this format and move the old properties inside of this block.
```
  restrict_pushes {
    blocks_creations = true
    push_restrictions = [
      "/some_user"
    ]
  }
 ```
The inclusion of the block is what enables the restrictions but with no actors specified, with the inner properties configuring the additional features. Removing `restrict_pushes` turns off the feature. e.g. enable the feature with the following to allow empty push_restrictions
```
  restrict_pushes {
  }
```

My preference is for solution 2 because I don't like that properties rely on other properties but aren't noticeably connected. (While doing this I've discovered that if you set `blocks_creations = true` but don't set the `push_restrictions` list, blocks_creations is never enabled because RestrictsPushes isn't true, and so the state is in constant flux.)

i.e. this will not work because the user has failed to set restrict_pushes = true
```
push_restrictions = [
"/someone"
]
```
That's why connecting them in a block would be better.

I'd love some feedback on this please. Thanks

**Comment by kfcampbell** [comment] 2024-01-05 18:47
@georgekaz I like your proposed solution and have responded on the PR; the main issue now is that major version changes in Terraform are somewhat onerous and require code to handle state migrations to avoid breaking users.

**Comment by georgekaz** [comment] 2024-02-22 11:30
Changes to support this (#2045) have been merged into the [v6](https://github.com/integrations/terraform-provider-github/releases/tag/v6.0.0) release so I think this issue can be closed.

**Closed** 2024-03-04 17:51 UTC
Labels: Type: Bug, r/branch_protection, Status: Needs info
