### ISSUE TITLE
[BUG]: github_branch_protection_v3.required-status-checks.checks - app_id changes all the time

### ISSUE THREAD

**Issue by bahag-klickst** [integrations/terraform-provider-github#1657] opened 2023-04-19 07:38 UTC
### Describe the need

Hej all,

We are in the middle of moving from the hashicorp/github provider to integrations/github provider and are also doing a major jump from v4.xx to latest 5.xx (as of writing/testing it was 5.22).

We are now facing an issue due to changing from contexts to checks in the required-status-checks block, because the new structure of the status checks is "context:app_id", but app_id changes with every run of our pipeline?

This is of course a bad thing, because it would lead to "unnecessary" changes with every terraform plan/apply.

### Relevant log output

```shell
Result of first plan:
---------------------
~ resource "github_branch_protection_v3" "main" {
        id                              = "repo-name:main"
        # (6 unchanged attributes hidden)

      ~ required_status_checks {
          ~ checks         = [
              - "Terraform:824642352016",
                # (1 unchanged element hidden)
            ]
          ~ contexts       = [
              - "Terraform",
            ]
            # (2 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Result of second plan, without any changes in between:
------------------------------------------------------
  ~ resource "github_branch_protection_v3" "main" {
        id                              = "repo-name:main"
        # (6 unchanged attributes hidden)

      ~ required_status_checks {
          ~ checks         = [
              - "Terraform:824635284400",
                # (1 unchanged element hidden)
            ]
          ~ contexts       = [
              - "Terraform",
            ]
            # (2 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

As one can see, the app_id changed from 824642352016 to 824635284400
Another plan then delivered 824642245200.

So the app_id is kind of generic and this makes it hard for us to use this new version.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment] 2023-04-20 22:37
@bahag-klickst can you provide an example of HCL that can be used to reproduce this issue?

**Comment by mmuth** [comment] 2023-04-25 20:43
> @bahag-klickst can you provide an example of HCL that can be used to reproduce this issue?

Hi! We have the very same issue. I created a minimal example (https://github.com/mmuth/github-terraform-provider-repro/blob/main/terraform/main.tf and the HCL: https://github.com/mmuth/github-terraform-provider-repro/blob/main/terraform/.terraform.lock.hcl)

It is always inconsistent, means a successful terraform apply followed by another apply will still try to change the Github repo. 
Sample log output of a retry:

```
# github_branch_protection_v3.master will be updated in-place
  ~ resource "github_branch_protection_v3" "main" {
        id                              = "sample-repo-with-statuschecks:main"
        # (6 unchanged attributes hidden)

      ~ required_status_checks {
          ~ checks         = [
              - "test-libraries",
              - "test-react",
              - "test-server",
              + "test-libraries:***OURAPPID***",
              + "test-react:***OURAPPID***",
              + "test-server:***OURAPPID***",
            ]
            # (3 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
we also tried around with `check:-1` and others but failed to ever recieve a repeatable consistent terraform.

New checks can basically be added, but we also noticed that we can never delete an existing check. It is converted to "any source" only but not removed. But this might also by a symptom of the same origin (?)...

**Comment by bahag-klickst** [comment] 2023-05-31 10:51
@kfcampbell 
Do you have any idea on when someone will grab this issue?

**Comment by kfcampbell** [comment] 2023-06-01 17:40
@bahag-klickst unfortunately our team very rarely gets the chance to pick up items like this as part of our daily work. We are very receptive to PRs though!

**Comment by GergelyKalmar** [comment] 2023-06-16 10:42
It seems that contexts have been deprecated but the alternative doesn't work at all. The issue with the branch protection resources isn't fixed either (see https://github.com/integrations/terraform-provider-github/issues/670). It seems that this provider is becoming really difficult to use even for basic things like applying proper branch protection.

**Comment by yaakov-h** [comment] 2023-07-06 07:41
I encountered the same issue today. Upon checking the raw API response, the `app_id` is correct, so the issue has to be in client code.

My gut sank when I realised that if the integer value changes every time the app runs... and converting it to hex makes it look quite suspicious...

Anyway I dug out my old Go docs and I'm 99% certain that the bug is here:

https://github.com/integrations/terraform-provider-github/blob/f8502b8bbff903cf427ecc2e60c4244f0dd8c150/github/resource_github_branch_protection_v3_utils.go#L63

The code tries to flatten the API response object (`{"context": "foo", "app_id": 123}`) into a single string (`foo:123`).

Unfortunately for this repo, that `AppID` field is optional, so it is [defined in go-github as *int64](https://github.com/google/go-github/blob/master/github/repos.go#L1051), i.e. as a pointer. In order to get the actual app_id value, it has to be dereferenced. (Of course, we cannot blindly reference it, because then we can crash when it is JSON `null` / Golang `nil`.)

There also seems to be some incorrect copy-pasting going on, as we are appending elemnts to `contexts` and assigning it back to `contexts`, but then we are also **appending elements to `contexts` and assigning to back to `checks`**.

These two loops look to me like they have a few problems that cause terraform to re-update the branch_protection_v3 resource on every run, and cleaning them up should fix this Issue as well as other problems:

https://github.com/integrations/terraform-provider-github/blob/f8502b8bbff903cf427ecc2e60c4244f0dd8c150/github/resource_github_branch_protection_v3_utils.go#L53-L64

**Closed** 2023-07-13 23:03 UTC
Labels: Type: Bug, Status: Up for grabs, Priority: Normal
